#include "ReactNativeAgeSignalsOnLoad.hpp"
#include <jni.h>

// `initialize` is generated by nitrogen into ReactNativeAgeSignalsOnLoad.cpp. It
// wraps `facebook::jni::initialize` itself and registers both the JNI natives and
// every autolinked HybridObject constructor, so this translation unit must not do
// either of those things again.
//
// Nitro 0.36.x replaces this entry point with `registerAllNatives()` called from
// inside a `facebook::jni::initialize` lambda. Changing nitro lines therefore
// means changing this file — see the compatibility table in README.md.
JNIEXPORT jint JNICALL JNI_OnLoad(JavaVM* vm, void*) {
  return margelo::nitro::agesignals::initialize(vm);
}
