plugins {
  id 'com.android.library'
  id 'org.jetbrains.kotlin.android'
}

apply from: '../nitrogen/generated/android/ReactNativeAgeSignals+autolinking.gradle'

group = 'com.margelo.nitro.agesignals'
version = '0.3.1'

android {
  namespace "com.margelo.nitro.agesignals"
  compileSdk 34

  defaultConfig {
    minSdk 24
    versionCode 1
    versionName "0.3.1"

    externalNativeBuild {
      cmake {
        cppFlags '-std=c++17'
        arguments '-DANDROID_STL=c++_shared'
      }
    }
  }

  externalNativeBuild {
    cmake {
      path 'CMakeLists.txt'
    }
  }

  lintOptions {
    abortOnError false
  }
}

dependencies {
  implementation 'com.margelo.nitro:react-native-nitro-modules:+'
  implementation 'com.google.android.play:age-signals:0.0.3'
  implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
}
